/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '../../../../src/app/bookings/bookings-edit.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/metadata/view';
import * as import5 from '@angular/core/src/linker/view_type';
import * as import6 from '@angular/core/src/change_detection/constants';
import * as import7 from '@angular/core/src/linker/component_factory';
import * as import8 from '../../../../src/app/bookings/BookingsService';
import * as import9 from '../../../../src/app/services/SecurityService';
import * as import10 from '@angular/router/src/router_state';
import * as import11 from '@angular/router/src/router';
import * as import12 from '../../../node_modules/@angular/forms/src/directives/default_value_accessor.ngfactory';
import * as import13 from '../../../node_modules/@angular/forms/src/directives/ng_model.ngfactory';
import * as import14 from '../../../node_modules/@angular/forms/src/directives/ng_control_status.ngfactory';
import * as import15 from '@angular/core/src/linker/view_container';
import * as import16 from '@angular/core/src/change_detection/change_detection_util';
import * as import17 from '@angular/core/src/linker/element_ref';
import * as import18 from '@angular/forms/src/directives/default_value_accessor';
import * as import19 from '@angular/forms/src/directives/control_value_accessor';
import * as import20 from '@angular/forms/src/directives/ng_model';
import * as import21 from '@angular/forms/src/directives/ng_control';
import * as import22 from '@angular/forms/src/directives/ng_control_status';
import * as import23 from '../../../node_modules/@angular/common/src/directives/ng_if.ngfactory';
import * as import24 from '@angular/core/src/linker/template_ref';
import * as import25 from '@angular/common/src/directives/ng_if';
export class Wrapper_BookingsEditComponent {
  /*private*/ _eventHandler:Function;
  context:import0.BookingsEditComponent;
  /*private*/ _changed:boolean;
  constructor(p0:any,p1:any,p2:any,p3:any) {
    this._changed = false;
    this.context = new import0.BookingsEditComponent(p0,p1,p2,p3);
  }
  ngOnDetach(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
    this.context.ngOnDestroy();
  }
  ngDoCheck(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    if (!throwOnChange) { if ((view.numberOfChecks === 0)) { this.context.ngOnInit(); } }
    return changed;
  }
  checkHost(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import1.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_BookingsEditComponent_Host:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,([] as any[]),{});
class View_BookingsEditComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import0.BookingsEditComponent>;
  _BookingsEditComponent_0_3:Wrapper_BookingsEditComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_BookingsEditComponent_Host0,renderType_BookingsEditComponent_Host,import5.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'bookings-edit',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_BookingsEditComponent0(this.viewUtils,this,0,this._el_0);
    this._BookingsEditComponent_0_3 = new Wrapper_BookingsEditComponent(this.injectorGet(import8.BookingsService,this.parentIndex),this.injectorGet(import9.SecurityService,this.parentIndex),this.injectorGet(import10.ActivatedRoute,this.parentIndex),this.injectorGet(import11.Router,this.parentIndex));
    this.compView_0.create(this._BookingsEditComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import7.ComponentRef_<any>(0,this,this._el_0,this._BookingsEditComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.BookingsEditComponent) && (0 === requestNodeIndex))) { return this._BookingsEditComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._BookingsEditComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
    this._BookingsEditComponent_0_3.ngOnDestroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const BookingsEditComponentNgFactory:import7.ComponentFactory<import0.BookingsEditComponent> = new import7.ComponentFactory<import0.BookingsEditComponent>('bookings-edit',View_BookingsEditComponent_Host0,import0.BookingsEditComponent);
const styles_BookingsEditComponent:any[] = ([] as any[]);
class View_BookingsEditComponent2 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _text_6:any;
  _el_7:any;
  _text_8:any;
  _text_9:any;
  _text_10:any;
  _el_11:any;
  _text_12:any;
  _el_13:any;
  _text_14:any;
  _el_15:any;
  _text_16:any;
  _text_17:any;
  _el_18:any;
  _text_19:any;
  _el_20:any;
  _DefaultValueAccessor_20_3:import12.Wrapper_DefaultValueAccessor;
  _NG_VALUE_ACCESSOR_20_4:any[];
  _NgModel_20_5:import13.Wrapper_NgModel;
  _NgControl_20_6:any;
  _NgControlStatus_20_7:import14.Wrapper_NgControlStatus;
  _text_21:any;
  _text_22:any;
  _text_23:any;
  _el_24:any;
  _text_25:any;
  _el_26:any;
  _text_27:any;
  _el_28:any;
  _text_29:any;
  _text_30:any;
  _el_31:any;
  _text_32:any;
  _el_33:any;
  _DefaultValueAccessor_33_3:import12.Wrapper_DefaultValueAccessor;
  _NG_VALUE_ACCESSOR_33_4:any[];
  _NgModel_33_5:import13.Wrapper_NgModel;
  _NgControl_33_6:any;
  _NgControlStatus_33_7:import14.Wrapper_NgControlStatus;
  _text_34:any;
  _text_35:any;
  _text_36:any;
  _el_37:any;
  _text_38:any;
  _el_39:any;
  _text_40:any;
  _el_41:any;
  _text_42:any;
  _text_43:any;
  _el_44:any;
  _text_45:any;
  _text_46:any;
  _text_47:any;
  _el_48:any;
  _text_49:any;
  _el_50:any;
  _text_51:any;
  _el_52:any;
  _text_53:any;
  _el_54:any;
  _text_55:any;
  _text_56:any;
  _text_57:any;
  _text_58:any;
  /*private*/ _expr_69:any;
  /*private*/ _expr_70:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import15.ViewContainer) {
    super(View_BookingsEditComponent2,renderType_BookingsEditComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_69 = import16.UNINITIALIZED;
    this._expr_70 = import16.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'div',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n                ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','row'),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'\n                    ',(null as any));
    this._el_4 = import3.createRenderElement(this.renderer,this._el_2,'div',new import3.InlineArray2(2,'class','col-xs-2'),(null as any));
    this._text_5 = this.renderer.createText(this._el_4,'Id',(null as any));
    this._text_6 = this.renderer.createText(this._el_2,'\n                    ',(null as any));
    this._el_7 = import3.createRenderElement(this.renderer,this._el_2,'div',new import3.InlineArray2(2,'class','col-xs-6'),(null as any));
    this._text_8 = this.renderer.createText(this._el_7,'',(null as any));
    this._text_9 = this.renderer.createText(this._el_2,'\n                ',(null as any));
    this._text_10 = this.renderer.createText(this._el_0,'\n\n                ',(null as any));
    this._el_11 = import3.createRenderElement(this.renderer,this._el_0,'hr',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_12 = this.renderer.createText(this._el_0,'\n                ',(null as any));
    this._el_13 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','row'),(null as any));
    this._text_14 = this.renderer.createText(this._el_13,'\n                    ',(null as any));
    this._el_15 = import3.createRenderElement(this.renderer,this._el_13,'div',new import3.InlineArray2(2,'class','col-xs-2'),(null as any));
    this._text_16 = this.renderer.createText(this._el_15,'Name',(null as any));
    this._text_17 = this.renderer.createText(this._el_13,'\n                    ',(null as any));
    this._el_18 = import3.createRenderElement(this.renderer,this._el_13,'div',new import3.InlineArray2(2,'class','col-xs-6'),(null as any));
    this._text_19 = this.renderer.createText(this._el_18,'\n                        ',(null as any));
    this._el_20 = import3.createRenderElement(this.renderer,this._el_18,'input',new import3.InlineArray4(4,'style','width: 100%','type','text'),(null as any));
    this._DefaultValueAccessor_20_3 = new import12.Wrapper_DefaultValueAccessor(this.renderer,new import17.ElementRef(this._el_20));
    this._NG_VALUE_ACCESSOR_20_4 = [this._DefaultValueAccessor_20_3.context];
    this._NgModel_20_5 = new import13.Wrapper_NgModel((null as any),(null as any),(null as any),this._NG_VALUE_ACCESSOR_20_4);
    this._NgControl_20_6 = this._NgModel_20_5.context;
    this._NgControlStatus_20_7 = new import14.Wrapper_NgControlStatus(this._NgControl_20_6);
    this._text_21 = this.renderer.createText(this._el_18,'\n                    ',(null as any));
    this._text_22 = this.renderer.createText(this._el_13,'\n                ',(null as any));
    this._text_23 = this.renderer.createText(this._el_0,'\n                ',(null as any));
    this._el_24 = import3.createRenderElement(this.renderer,this._el_0,'hr',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_25 = this.renderer.createText(this._el_0,'\n                ',(null as any));
    this._el_26 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','row'),(null as any));
    this._text_27 = this.renderer.createText(this._el_26,'\n                    ',(null as any));
    this._el_28 = import3.createRenderElement(this.renderer,this._el_26,'div',new import3.InlineArray2(2,'class','col-xs-2'),(null as any));
    this._text_29 = this.renderer.createText(this._el_28,'Description',(null as any));
    this._text_30 = this.renderer.createText(this._el_26,'\n                    ',(null as any));
    this._el_31 = import3.createRenderElement(this.renderer,this._el_26,'div',new import3.InlineArray2(2,'class','col-xs-6'),(null as any));
    this._text_32 = this.renderer.createText(this._el_31,'\n                        ',(null as any));
    this._el_33 = import3.createRenderElement(this.renderer,this._el_31,'input',new import3.InlineArray4(4,'style','width: 100%','type','text'),(null as any));
    this._DefaultValueAccessor_33_3 = new import12.Wrapper_DefaultValueAccessor(this.renderer,new import17.ElementRef(this._el_33));
    this._NG_VALUE_ACCESSOR_33_4 = [this._DefaultValueAccessor_33_3.context];
    this._NgModel_33_5 = new import13.Wrapper_NgModel((null as any),(null as any),(null as any),this._NG_VALUE_ACCESSOR_33_4);
    this._NgControl_33_6 = this._NgModel_33_5.context;
    this._NgControlStatus_33_7 = new import14.Wrapper_NgControlStatus(this._NgControl_33_6);
    this._text_34 = this.renderer.createText(this._el_31,'\n                    ',(null as any));
    this._text_35 = this.renderer.createText(this._el_26,'\n                ',(null as any));
    this._text_36 = this.renderer.createText(this._el_0,'\n                ',(null as any));
    this._el_37 = import3.createRenderElement(this.renderer,this._el_0,'hr',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_38 = this.renderer.createText(this._el_0,'\n                ',(null as any));
    this._el_39 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','row'),(null as any));
    this._text_40 = this.renderer.createText(this._el_39,'\n                    ',(null as any));
    this._el_41 = import3.createRenderElement(this.renderer,this._el_39,'div',new import3.InlineArray2(2,'class','col-xs-2'),(null as any));
    this._text_42 = this.renderer.createText(this._el_41,'Timestamp',(null as any));
    this._text_43 = this.renderer.createText(this._el_39,'\n                    ',(null as any));
    this._el_44 = import3.createRenderElement(this.renderer,this._el_39,'div',new import3.InlineArray2(2,'class','col-xs-6'),(null as any));
    this._text_45 = this.renderer.createText(this._el_44,'',(null as any));
    this._text_46 = this.renderer.createText(this._el_39,'\n                ',(null as any));
    this._text_47 = this.renderer.createText(this._el_0,'\n                ',(null as any));
    this._el_48 = import3.createRenderElement(this.renderer,this._el_0,'hr',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_49 = this.renderer.createText(this._el_0,'\n                ',(null as any));
    this._el_50 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','row'),(null as any));
    this._text_51 = this.renderer.createText(this._el_50,'\n                    ',(null as any));
    this._el_52 = import3.createRenderElement(this.renderer,this._el_50,'div',new import3.InlineArray2(2,'class','col-xs-2'),(null as any));
    this._text_53 = this.renderer.createText(this._el_52,'\n                        ',(null as any));
    this._el_54 = import3.createRenderElement(this.renderer,this._el_52,'button',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_55 = this.renderer.createText(this._el_54,'Update',(null as any));
    this._text_56 = this.renderer.createText(this._el_52,'\n                    ',(null as any));
    this._text_57 = this.renderer.createText(this._el_50,'\n                ',(null as any));
    this._text_58 = this.renderer.createText(this._el_0,'\n            ',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_20,new import3.InlineArray8(6,'ngModelChange',(null as any),'input',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_20));
    this._NgModel_20_5.subscribe(this,this.eventHandler(this.handleEvent_20),true);
    var disposable_1:Function = import3.subscribeToRenderElement(this,this._el_33,new import3.InlineArray8(6,'ngModelChange',(null as any),'input',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_33));
    this._NgModel_33_5.subscribe(this,this.eventHandler(this.handleEvent_33),true);
    var disposable_2:Function = import3.subscribeToRenderElement(this,this._el_54,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_54));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._text_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._text_22,
      this._text_23,
      this._el_24,
      this._text_25,
      this._el_26,
      this._text_27,
      this._el_28,
      this._text_29,
      this._text_30,
      this._el_31,
      this._text_32,
      this._el_33,
      this._text_34,
      this._text_35,
      this._text_36,
      this._el_37,
      this._text_38,
      this._el_39,
      this._text_40,
      this._el_41,
      this._text_42,
      this._text_43,
      this._el_44,
      this._text_45,
      this._text_46,
      this._text_47,
      this._el_48,
      this._text_49,
      this._el_50,
      this._text_51,
      this._el_52,
      this._text_53,
      this._el_54,
      this._text_55,
      this._text_56,
      this._text_57,
      this._text_58
    ]
    ),[
      disposable_0,
      disposable_1,
      disposable_2
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import18.DefaultValueAccessor) && (20 === requestNodeIndex))) { return this._DefaultValueAccessor_20_3.context; }
    if (((token === import19.NG_VALUE_ACCESSOR) && (20 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_20_4; }
    if (((token === import20.NgModel) && (20 === requestNodeIndex))) { return this._NgModel_20_5.context; }
    if (((token === import21.NgControl) && (20 === requestNodeIndex))) { return this._NgControl_20_6; }
    if (((token === import22.NgControlStatus) && (20 === requestNodeIndex))) { return this._NgControlStatus_20_7.context; }
    if (((token === import18.DefaultValueAccessor) && (33 === requestNodeIndex))) { return this._DefaultValueAccessor_33_3.context; }
    if (((token === import19.NG_VALUE_ACCESSOR) && (33 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_33_4; }
    if (((token === import20.NgModel) && (33 === requestNodeIndex))) { return this._NgModel_33_5.context; }
    if (((token === import21.NgControl) && (33 === requestNodeIndex))) { return this._NgControl_33_6; }
    if (((token === import22.NgControlStatus) && (33 === requestNodeIndex))) { return this._NgControlStatus_33_7.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._DefaultValueAccessor_20_3.ngDoCheck(this,this._el_20,throwOnChange);
    const currVal_20_1_0:any = this.parentView.parentView.context.Booking.Name;
    this._NgModel_20_5.check_model(currVal_20_1_0,throwOnChange,false);
    this._NgModel_20_5.ngDoCheck(this,this._el_20,throwOnChange);
    this._NgControlStatus_20_7.ngDoCheck(this,this._el_20,throwOnChange);
    this._DefaultValueAccessor_33_3.ngDoCheck(this,this._el_33,throwOnChange);
    const currVal_33_1_0:any = this.parentView.parentView.context.Booking.Description;
    this._NgModel_33_5.check_model(currVal_33_1_0,throwOnChange,false);
    this._NgModel_33_5.ngDoCheck(this,this._el_33,throwOnChange);
    this._NgControlStatus_33_7.ngDoCheck(this,this._el_33,throwOnChange);
    const currVal_69:any = import3.inlineInterpolate(1,'',this.parentView.parentView.context.Booking.Id,'');
    if (import3.checkBinding(throwOnChange,this._expr_69,currVal_69)) {
      this.renderer.setText(this._text_8,currVal_69);
      this._expr_69 = currVal_69;
    }
    this._NgControlStatus_20_7.checkHost(this,this,this._el_20,throwOnChange);
    this._NgControlStatus_33_7.checkHost(this,this,this._el_33,throwOnChange);
    const currVal_70:any = import3.inlineInterpolate(1,'',this.parentView.parentView.context.Booking.Timestamp,'');
    if (import3.checkBinding(throwOnChange,this._expr_70,currVal_70)) {
      this.renderer.setText(this._text_45,currVal_70);
      this._expr_70 = currVal_70;
    }
  }
  destroyInternal():void {
    this._NgModel_20_5.ngOnDestroy();
    this._NgModel_33_5.ngOnDestroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  handleEvent_20(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._DefaultValueAccessor_20_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'ngModelChange')) {
      const pd_sub_0:any = ((<any>(this.parentView.parentView.context.Booking.Name = $event)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_33(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._DefaultValueAccessor_33_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'ngModelChange')) {
      const pd_sub_0:any = ((<any>(this.parentView.parentView.context.Booking.Description = $event)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_54(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.parentView.parentView.context.Update()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}
class View_BookingsEditComponent1 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _text_8:any;
  _text_9:any;
  _el_10:any;
  _text_11:any;
  _anchor_12:any;
  /*private*/ _vc_12:import15.ViewContainer;
  _TemplateRef_12_5:any;
  _NgIf_12_6:import23.Wrapper_NgIf;
  _text_13:any;
  _text_14:any;
  _text_15:any;
  /*private*/ _expr_19:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import15.ViewContainer) {
    super(View_BookingsEditComponent1,renderType_BookingsEditComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_19 = import16.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'div',new import3.InlineArray2(2,'class','col-md-12'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','panel panel-default'),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_4 = import3.createRenderElement(this.renderer,this._el_2,'div',new import3.InlineArray2(2,'class','panel-heading'),(null as any));
    this._text_5 = this.renderer.createText(this._el_4,'\n            ',(null as any));
    this._el_6 = import3.createRenderElement(this.renderer,this._el_4,'h3',new import3.InlineArray2(2,'class','panel-title'),(null as any));
    this._text_7 = this.renderer.createText(this._el_6,'',(null as any));
    this._text_8 = this.renderer.createText(this._el_4,'\n        ',(null as any));
    this._text_9 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_10 = import3.createRenderElement(this.renderer,this._el_2,'div',new import3.InlineArray2(2,'class','panel-body'),(null as any));
    this._text_11 = this.renderer.createText(this._el_10,'\n            ',(null as any));
    this._anchor_12 = this.renderer.createTemplateAnchor(this._el_10,(null as any));
    this._vc_12 = new import15.ViewContainer(12,10,this,this._anchor_12);
    this._TemplateRef_12_5 = new import24.TemplateRef_(this,12,this._anchor_12);
    this._NgIf_12_6 = new import23.Wrapper_NgIf(this._vc_12.vcRef,this._TemplateRef_12_5);
    this._text_13 = this.renderer.createText(this._el_10,'\n        ',(null as any));
    this._text_14 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._text_15 = this.renderer.createText(this._el_0,'\n',(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._anchor_12,
      this._text_13,
      this._text_14,
      this._text_15
    ]
    ),(null as any));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import24.TemplateRef) && (12 === requestNodeIndex))) { return this._TemplateRef_12_5; }
    if (((token === import25.NgIf) && (12 === requestNodeIndex))) { return this._NgIf_12_6.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_12_0_0:any = this.parentView.context.Booking;
    this._NgIf_12_6.check_ngIf(currVal_12_0_0,throwOnChange,false);
    this._NgIf_12_6.ngDoCheck(this,this._anchor_12,throwOnChange);
    this._vc_12.detectChangesInNestedViews(throwOnChange);
    const currVal_19:any = import3.inlineInterpolate(1,'',this.parentView.context.message,'');
    if (import3.checkBinding(throwOnChange,this._expr_19,currVal_19)) {
      this.renderer.setText(this._text_7,currVal_19);
      this._expr_19 = currVal_19;
    }
  }
  destroyInternal():void {
    this._vc_12.destroyNestedViews();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  createEmbeddedViewInternal(nodeIndex:number):import1.AppView<any> {
    if ((nodeIndex == 12)) { return new View_BookingsEditComponent2(this.viewUtils,this,12,this._anchor_12,this._vc_12); }
    return (null as any);
  }
}
var renderType_BookingsEditComponent:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,styles_BookingsEditComponent,{});
export class View_BookingsEditComponent0 extends import1.AppView<import0.BookingsEditComponent> {
  _anchor_0:any;
  /*private*/ _vc_0:import15.ViewContainer;
  _TemplateRef_0_5:any;
  _NgIf_0_6:import23.Wrapper_NgIf;
  _text_1:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_BookingsEditComponent0,renderType_BookingsEditComponent,import5.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._anchor_0 = this.renderer.createTemplateAnchor(parentRenderNode,(null as any));
    this._vc_0 = new import15.ViewContainer(0,(null as any),this,this._anchor_0);
    this._TemplateRef_0_5 = new import24.TemplateRef_(this,0,this._anchor_0);
    this._NgIf_0_6 = new import23.Wrapper_NgIf(this._vc_0.vcRef,this._TemplateRef_0_5);
    this._text_1 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._anchor_0,
      this._text_1
    ]
    ),(null as any));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import24.TemplateRef) && (0 === requestNodeIndex))) { return this._TemplateRef_0_5; }
    if (((token === import25.NgIf) && (0 === requestNodeIndex))) { return this._NgIf_0_6.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0_0_0:any = this.context.securityService.IsAuthorized();
    this._NgIf_0_6.check_ngIf(currVal_0_0_0,throwOnChange,false);
    this._NgIf_0_6.ngDoCheck(this,this._anchor_0,throwOnChange);
    this._vc_0.detectChangesInNestedViews(throwOnChange);
  }
  destroyInternal():void {
    this._vc_0.destroyNestedViews();
  }
  createEmbeddedViewInternal(nodeIndex:number):import1.AppView<any> {
    if ((nodeIndex == 0)) { return new View_BookingsEditComponent1(this.viewUtils,this,0,this._anchor_0,this._vc_0); }
    return (null as any);
  }
}